### ISSUE TITLE
if windows can work well , it will be better, so how to fix it?

### ISSUE THREAD

**Issue by aresbit** [Haider-Ali-Dev/gog#1]
Error: GoogBrowserError(Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" })
thank you

**Comment by haiderlikesrust** [comment]
Next version will be v1.0.0, in which I'll add more commands and goog will be supported with all Operating Systems.

**Comment by haiderlikesrust** [comment]
Btw I haven't started working on os compatibility if you want to add that you can submit a pull request

**Comment by haiderlikesrust** [comment]
Added windows support

**Comment by aresbit** [comment]
> Added windows support

thanks, bro

**Comment by aresbit** [comment]
but, err like this : system can not find file
Searching for "rust" on your defualt browser
Error: GoogBrowserError(Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" })

**Comment by haiderlikesrust** [comment]
What is your default browser? Looks like there is a bug in the code

**Comment by aresbit** [comment]
my default browser is chrome, maybe windows's reason?

**Comment by aresbit** [comment]
oh my god, I see, because using windows terminal， bro， can you tell me why

**Comment by aresbit** [comment]
oh no,  when using git bash,  err again,

**Comment by haiderlikesrust** [comment]
Will be fixed just be patient.
